language: java

addons:
  apt:
    packages:
    - openjdk-6-jdk

jdk:
- oraclejdk8

before_install:
- echo "Downloading Nacos 0.2.1"
  && wget https://github.com/alibaba/nacos/releases/download/0.2.1/nacos-server-0.2.1.zip
  && unzip -q nacos-server-0.2.1.zip
  && export NACOS_HOME=$PWD/nacos
  && export PATH=$NACOS_HOME/bin:$PATH

before_script:
- bash $NACOS_HOME/bin/startup.sh -m standalone
- sleep 10
- netstat -an|grep nacos|grep -v grep

script:
- cat $NACOS_HOME/logs/*
- free -m
- ps -ef|grep nacos|grep -v grep 
- sleep 10
- netstat -an|grep 8848
- curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=127.0.0.1&port=8080'
- curl -X GET 'http://127.0.0.1:8848/nacos/v1/ns/instances?serviceName=nacos.naming.serviceName'

after_script:
- bash $NACOS_HOME/bin/shutdown.sh
